language: node_js
node_js:
  - '8'
dist: trusty
addons:
  chrome: stable
env:
  CC_TEST_REPORTER_ID: 9be6d10a869826c526f2fd01eaaf884a4da46edcc8cc769a002d37a121833e97
global:
  - export NODE_ENV=test
before_install: cd src
install:
  - npm install
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE "so-lite-dev";' -U postgres
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  # - npm test
  - nyc --reporter=lcov yarn run test
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email: false
after_success: npm run coveralls
